{
 "title": "Oracle App-Specific -- Database System Level -- Update",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Host Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (host_name)"
    }
   ]
  },
  {
   "title": "Instance Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (instance_name)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (uptime)"
    }
   ]
  },
  {
   "title": "Startup Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (stime)"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "calculatedInterval": "10m", "expr": "oracledb_up" }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"NUM_CPUS\"}"
    }
   ]
  },
  {
   "title": "DB CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "rate(oracledb_os_value{stat_name=\"BUSY_TIME\"}[2m]) / ignoring(stat_name) oracledb_os_value{stat_name=\"NUM_CPUS\"}  /  ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_os_value{stat_name=\"BUSY_TIME\"}[2m]) / ignoring(stat_name) oracledb_os_value{stat_name=\"NUM_CPUS\"}  /  ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "busy"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"IOWAIT_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "iowait"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"SYS_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "sys"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"USER_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "user"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"NICE_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "Number of CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"NUM_CPU_CORES\"}"
    }
   ]
  },
  {
   "title": "Total Physical Memory(OS)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"PHYSICAL_MEMORY_BYTES\"} "
    }
   ]
  },
  {
   "title": "SGA Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "oracledb_sga_total_b" }
   ]
  },
  {
   "title": "Memory Usage(OS)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"FREE_MEMORY_BYTES\"} / ignoring(stat_name) oracledb_os_value{stat_name=\"PHYSICAL_MEMORY_BYTES\"}"
    }
   ]
  },
  {
   "title": "SGA Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "oracledb_sga_used_b / ignoring(inst_id) oracledb_sga_total_b"
    }
   ]
  },
  {
   "title": "SGA Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "oracledb_sga_free_b", "legendFormat": "sga free" },
    { "expr": "oracledb_sga_used_b", "legendFormat": "sga used" }
   ]
  },
  {
   "title": "Active User Session",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Sessions by Machine",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
   "targets": [
    { "expr": "oracledb_session_mvalue", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Total Physical Read/Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_value{name=\"physical read total bytes\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"physical write total bytes\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Inactive User Session",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"INACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Active Background Session",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"BACKGROUND\"}"
    }
   ]
  },
  {
   "title": "Total Physical Read/Write IO Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_value{name=\"physical read total IO requests\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"physical write total IO requests\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "User Activity Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "requests per minute" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_value{name=\"user calls\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"user commits\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"user rollbacks\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"execute count\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "User Activity Hourly",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oracledb_system_value{name=\"execute count\"}[1h])",
     "legendFormat": "execute count"
    },
    {
     "expr": "increase(oracledb_system_value{name=\"user calls\"}[1h])",
     "legendFormat": "user calls"
    },
    {
     "expr": "increase(oracledb_system_value{name=\"user commits\"}[1h])",
     "legendFormat": "user commits"
    },
    {
     "expr": "increase(oracledb_system_value{name=\"user rollbacks\"}[1h])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(oracledb_network_received_from_client_b[5m])",
     "legendFormat": "inbound"
    },
    {
     "expr": "irate(oracledb_network_sent_to_client_b[5m])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "System: Amount of time spent in the wait class",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "oracledb_system_wait_time_waited",
     "legendFormat": "{{wait_class}}"
    }
   ]
  },
  {
   "title": "Network Traffic Hourly",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(oracledb_network_received_from_client_b[1h])",
     "legendFormat": "inbound"
    },
    {
     "expr": "increase(oracledb_network_sent_to_client_b[1h])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "System: Amount of time spent in the wait class",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "oracledb_session_wait_seconds_in_wait"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"BACKGROUND\"}",
     "legendFormat": "active background"
    },
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"USER\"}",
     "legendFormat": "active user"
    },
    {
     "expr": "oracledb_session_value{status=\"INACTIVE\", type=\"USER\"}",
     "legendFormat": "inactive user"
    }
   ]
  },
  {
   "title": "Process Load",
   "type": "graph",
   "description": "Number of processes running or waiting on the run queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[1m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[1m]))",
     "legendFormat": "Load 1m"
    },
    {
     "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[5m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[5m]))",
     "legendFormat": "Load 5m"
    },
    {
     "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[15m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[15m]))",
     "legendFormat": "Load 15m"
    }
   ]
  }
 ]
}