
services:
  prometheus:
    image: prom/prometheus@sha256:5550dc63da361dc30f6fe02ac0e4dfc736ededfef3c8d12a634db04a67824d78
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  free26ai:
    image: gvenzl/oracle-free:23.26.2-slim-faststart
    container_name: free26ai
    ports:
      - 127.0.0.1:1521:1521
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "printf \"whenever sqlerror exit failure\\nset heading off feedback off pagesize 0 verify off\\nselect 'READY' from dual;\\nexit;\\n\" | sqlplus -s \"pdbadmin/$${ORACLE_PASSWORD}@//localhost:1521/FREEPDB1\" | grep -q READY",
        ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  second26ai:
    image: gvenzl/oracle-free:23.26.2-slim-faststart
    container_name: second26ai
    ports:
      - 127.0.0.1:1522:1521
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "printf \"whenever sqlerror exit failure\\nset heading off feedback off pagesize 0 verify off\\nselect 'READY' from dual;\\nexit;\\n\" | sqlplus -s \"pdbadmin/$${ORACLE_PASSWORD}@//localhost:1521/FREEPDB1\" | grep -q READY",
        ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  exporter:
    image: container-registry.oracle.com/database/observability-exporter:2.4.2
    container_name: exporter
    command:
      - --config.file=/exporter/${COMPOSE_CONFIG_FILE:-config.yaml}
    ports:
      - 9161:9161
    environment:
    # If using wallet, these can bet set. Otherwise, not necessary to supply.
    - TNS_ADMIN=${TNS_ADMIN}
    - ADB_USERNAME=${ADB_USERNAME}
    - ADB_PASSWORD=${ADB_PASSWORD}
    - ADB_TNS_ALIAS=${ADB_TNS_ALIAS}
    - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_USERNAME=pdbadmin
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_CONNECT_STRING=free26ai:1521/freepdb1
    volumes:
      - ./exporter:/exporter
      - ./wallet:/exporter/wallet

    depends_on: 
      free26ai:
        condition: service_healthy
      second26ai:
        condition: service_healthy

volumes:
  prom_data:
