{
 "title": "Oracle App-Specific -- Database System Level - v1.1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(oracledb_instance_dummy, inst_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database and Instance Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_database_version_dummy"
    }
   ]
  },
  {
   "title": "Instance Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy{inst_id=\"[[Instance]]\"}) by (instance_name)"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "calculatedInterval": "10m", "expr": "oracledb_up" }
   ]
  },
  {
   "title": "RAC DB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "calculatedInterval": "10m", "expr": "oracledb_database_rac_value" }
   ]
  },
  {
   "title": "Host Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (host_name)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (uptime)"
    }
   ]
  },
  {
   "title": "Startup Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(oracledb_instance_dummy) by (stime)"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"NUM_CPUS\"}"
    }
   ]
  },
  {
   "title": "DB CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(oracledb_os_value{stat_name=\"BUSY_TIME\"}[2m]) / ignoring(stat_name) oracledb_os_value{stat_name=\"NUM_CPUS\"}  /  ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "BUSY_TIME: Number of hundredths of a second that a processor has been busy executing user or kernel code, totalled over all processors\n\nIO_WAIT_TIME: Number of hundredths of a second that a processor has been waiting for I/O to complete, totalled over all processors\n\nSYS_TIME: Number of hundredths of a second that a processor has been busy executing kernel code, totalled over all processors\n\nUSER_TIME: Number of hundredths of a second that a processor has been busy executing user code, totalled over all processors\n\nNICE_TIME: Number of hundredths of a second that a processor has been busy executing low-priority user code, totalled over all processors\n\n",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_os_value{stat_name=\"BUSY_TIME\"}[2m]) / ignoring(stat_name) oracledb_os_value{stat_name=\"NUM_CPUS\"}  /  ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "busy"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"IOWAIT_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "iowait"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"SYS_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "sys"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"USER_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "user"
    },
    {
     "expr": "rate(oracledb_os_value{stat_name=\"NICE_TIME\"}[2m]) / ignoring(stat_name) rate(job:os:total_cpu_elpased_time[2m])",
     "legendFormat": "nice"
    }
   ]
  },
  {
   "title": "Number of CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"NUM_CPU_CORES\"}"
    }
   ]
  },
  {
   "title": "Total Physical Memory(OS)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"PHYSICAL_MEMORY_BYTES\"} "
    }
   ]
  },
  {
   "title": "SGA Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "oracledb_sga_total_b" }
   ]
  },
  {
   "title": "Memory Usage(OS)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_os_value{stat_name=\"FREE_MEMORY_BYTES\"} / ignoring(stat_name) oracledb_os_value{stat_name=\"PHYSICAL_MEMORY_BYTES\"}"
    }
   ]
  },
  {
   "title": "SGA Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sga_used_b / ignoring(inst_id) oracledb_sga_total_b"
    }
   ]
  },
  {
   "title": "SGA Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "oracledb_sga_free_b", "legendFormat": "sga free" },
    { "expr": "oracledb_sga_used_b", "legendFormat": "sga used" }
   ]
  },
  {
   "title": "Total Physical Read/Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_stat_value{name=\"physical read total bytes\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(oracledb_system_stat_value{name=\"physical write total bytes\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Total Physical Read/Write IO Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_stat_value{name=\"physical read total IO requests\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(oracledb_system_stat_value{name=\"physical write total IO requests\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Active User Session",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"BACKGROUND\"}",
     "legendFormat": "active background"
    },
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"USER\"}",
     "legendFormat": "active user"
    },
    {
     "expr": "oracledb_session_value{status=\"INACTIVE\", type=\"USER\"}",
     "legendFormat": "inactive user"
    }
   ]
  },
  {
   "title": "Sessions by Machine",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_session_mvalue{inst_id=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Inactive User Session",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"INACTIVE\", type=\"USER\"}"
    }
   ]
  },
  {
   "title": "Active Background Session",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_session_value{status=\"ACTIVE\", type=\"BACKGROUND\"}"
    }
   ]
  },
  { "title": "User Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "User Activity Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none", "label": "requests per minute" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_stat_value{name=\"user calls\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_stat_value{name=\"user commits\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"user rollbacks\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(oracledb_system_value{name=\"execute count\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "User Activity Hourly",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oracledb_system_stat_value{name=\"execute count\"}[1h])",
     "legendFormat": "execute count"
    },
    {
     "expr": "increase(oracledb_system_stat_value{name=\"user calls\"}[1h])",
     "legendFormat": "user calls"
    },
    {
     "expr": "increase(oracledb_system_value{name=\"user commits\"}[1h])",
     "legendFormat": "user commits"
    },
    {
     "expr": "increase(oracledb_system_value{name=\"user rollbacks\"}[1h])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(oracledb_network_received_from_client_b[5m])",
     "legendFormat": "inbound"
    },
    {
     "expr": "irate(oracledb_network_sent_to_client_b[5m])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Network Traffic Hourly",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(oracledb_network_received_from_client_b[1h])",
     "legendFormat": "inbound"
    },
    {
     "expr": "increase(oracledb_network_sent_to_client_b[1h])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Wait Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "System: Amount of time spent in the wait class",
     "type": "table",
     "gridPos": { "h": 20, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "oracledb_system_wait_time_waited / 100",
       "legendFormat": "{{wait_class}}"
      }
     ]
    },
    {
     "title": "Session: Amount of time spent in the wait class",
     "type": "table",
     "description": "Seconds spent in the current wait condition",
     "gridPos": { "h": 20, "w": 15, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "oracledb_session_wait_seconds_in_wait"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Load",
     "type": "graph",
     "description": "Number of processes running or waiting on the run queue",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[1m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[1m]))",
       "legendFormat": "Load 1m"
      },
      {
       "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[5m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[5m]))",
       "legendFormat": "Load 5m"
      },
      {
       "expr": " sum(sum_over_time(oracledb_os_value{stat_name=\"LOAD\"}[15m])) / sum(count_over_time(oracledb_os_value{stat_name=\"LOAD\"}[15m]))",
       "legendFormat": "Load 15m"
      }
     ]
    }
   ]
  }
 ]
}