{
 "title": "Oracle App-specific - Query Level - v1.1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(oracledb_instance_dummy, inst_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SQL Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQL ordered by Elapsed Time (Top 10)",
   "type": "table",
   "description": "%Total - Elapsed Time as a percentage of Total DB time\n\n%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "oracledb_sql_query_elapsed_time_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_elapsed_time_order_executions"
    },
    {
     "expr": "oracledb_sql_query_elapsed_time_order_elapsed_time / on(inst_id, instance, job) group_left oracledb_system_time_value{stat_name=\"DB time\"}"
    },
    {
     "expr": "oracledb_sql_query_elapsed_time_order_cpu_time / oracledb_sql_query_elapsed_time_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_elapsed_time_order_user_io_wait_time / oracledb_sql_query_elapsed_time_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by CPU Time (Top 10)",
   "type": "table",
   "description": "%Total - CPU Time as a percentage of Total DB CPU\n\n%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "oracledb_sql_query_cpu_time_order_cpu_time"
    },
    {
     "expr": "oracledb_sql_query_cpu_time_order_executions"
    },
    {
     "expr": "oracledb_sql_query_cpu_time_order_elapsed_time / on(inst_id, instance, job) group_left oracledb_system_time_value{stat_name=\"DB CPU\"}"
    },
    {
     "expr": "oracledb_sql_query_cpu_time_order_cpu_time / oracledb_sql_query_cpu_time_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_cpu_time_order_user_io_wait_time / oracledb_sql_query_cpu_time_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by User I/O Wait Time (Top 10)",
   "type": "table",
   "description": "%Total - User I/O Time as a percentage of Total User I/O Wait time\n\n%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "oracledb_sql_query_uio_time_order_user_io_wait_time"
    },
    {
     "expr": "oracledb_sql_query_uio_time_order_executions"
    },
    {
     "expr": "oracledb_sql_query_uio_time_order_user_io_wait_time / on(inst_id, instance, job) group_left oracledb_sql_query_total_io_wait_time"
    },
    {
     "expr": "oracledb_sql_query_uio_time_order_cpu_time / oracledb_sql_query_uio_time_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_uio_time_order_user_io_wait_time / oracledb_sql_query_uio_time_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by Gets (Top 10)",
   "type": "table",
   "description": "%Total - Buffer Gets as a percentage of Total Buffer Gets\n\n%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "oracledb_sql_query_gets_order_buffer_gets"
    },
    {
     "expr": "oracledb_sql_query_gets_order_executions"
    },
    {
     "expr": "oracledb_sql_query_gets_order_buffer_gets / on(inst_id, instance, job) group_left oracledb_sql_query_total_buffer_gets"
    },
    {
     "expr": "oracledb_sql_query_gets_order_cpu_time / oracledb_sql_query_gets_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_gets_order_user_io_wait_time / oracledb_sql_query_gets_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by Reads (Top 10)",
   "type": "table",
   "description": "%Total - Physical Reads as a percentage of Total Disk Reads\n\n%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "oracledb_sql_query_reads_order_disk_reads"
    },
    {
     "expr": "oracledb_sql_query_reads_order_executions"
    },
    {
     "expr": "oracledb_sql_query_reads_order_disk_reads / on(inst_id, instance, job) group_left oracledb_sql_query_total_disk_reads"
    },
    {
     "expr": "oracledb_sql_query_reads_order_cpu_time / oracledb_sql_query_reads_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_reads_order_user_io_wait_time / oracledb_sql_query_reads_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by Executions (Top 10)",
   "type": "table",
   "description": "%CPU - CPU Time as a percentage of Elapsed Time\n\n%IO - User I/O Time as a percentage of Elapsed Time",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "oracledb_sql_query_exec_order_rows_processed"
    },
    {
     "expr": "oracledb_sql_query_exec_order_executions"
    },
    {
     "expr": "oracledb_sql_query_exec_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_exec_order_cpu_time / oracledb_sql_query_exec_order_elapsed_time"
    },
    {
     "expr": "oracledb_sql_query_exec_order_user_io_wait_time / oracledb_sql_query_exec_order_elapsed_time"
    }
   ]
  },
  {
   "title": "SQL Ordered by Parse Calls (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "oracledb_sql_query_parse_calls_order_parse_calls"
    },
    {
     "expr": "oracledb_sql_query_parse_calls_order_executions"
    },
    {
     "expr": "oracledb_sql_query_parse_calls_order_parse_calls / on (inst_id, instance, job) group_left oracledb_sql_query_total_parse_calls"
    }
   ]
  }
 ]
}