{
 "title": "Oracle App-Specific -- Concurrency Level - v1.1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Foreground Wait Class",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_class_waits_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_class_total_wait_time_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_class_avg_wait_time_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_class_total_wait_time_fg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysstat_db_time"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_class_timeouts_fg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysevent_total_timeout"
    }
   ]
  },
  {
   "title": "Foreground Wait Class - Wait Time (s) [Accumulate]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_class_total_wait_time_fg",
     "legendFormat": "{{wait_class_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Class - Wait Time (s) [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_foreground_wait_class_total_wait_time_fg[2m])",
     "legendFormat": "{{wait_class_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Class - Wait Count [accumulte]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_class_waits_fg",
     "legendFormat": "{{wait_class_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Class - Wait Count [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_foreground_wait_class_waits_fg[2m])",
     "legendFormat": "{{wait_class_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Class - Average Wait Time (s) [Accumulate]",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_class_avg_wait_time_fg",
     "legendFormat": "{{wait_class_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Event",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_event_waits_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_event_time_waited_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_event_average_wait_fg"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_event_time_waited_fg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysstat_db_time"
    },
    {
     "expr": "oracledb_concurrency_foreground_wait_event_timeouts_fg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysevent_total_timeout"
    }
   ]
  },
  {
   "title": "Foreground Wait Event - Wait Time (s) [Accumulate]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_event_time_waited_fg",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Event - Wait Time (s) [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_foreground_wait_event_time_waited_fg[2m])",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Event - Wait Count [Accumulate]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_event_waits_fg",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Event - Wait Count [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_foreground_wait_event_waits_fg[2m])",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Foreground Wait Event - Average Wait Time (s) [Accumulate]",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_concurrency_foreground_wait_event_average_wait_fg",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Background Wait Event",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "oracledb_concurrency_background_wait_event_waits_bg"
    },
    {
     "expr": "oracledb_concurrency_background_wait_event_time_waited_bg"
    },
    {
     "expr": "oracledb_concurrency_background_wait_event_average_wait_bg"
    },
    {
     "expr": "oracledb_concurrency_background_wait_event_time_waited_bg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysstat_total_time_waited_bg"
    },
    {
     "expr": "oracledb_concurrency_background_wait_event_timeouts_bg / on(con_id, inst_id, instance, job) group_left oracledb_concurrency_sysevent_total_timeout"
    }
   ]
  },
  {
   "title": "Background Wait Event - Wait Time (s) [Accumulate]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_background_wait_event_time_waited_bg",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Background Wait Event - Wait Time (s) [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_background_wait_event_time_waited_bg[2m])",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Background Wait Event - Wait Count [Accumulate]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracledb_concurrency_background_wait_event_waits_bg",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Background Wait Event - Wait Count [2m Delta]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(oracledb_concurrency_background_wait_event_waits_bg[2m])",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Background Wait Event - Average Wait Time (s) [Accumulate]",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_concurrency_background_wait_event_average_wait_bg",
     "legendFormat": "{{event_name}}"
    }
   ]
  }
 ]
}