dataSourceMyFirstDB :
  serviceName : myservicename1
  userName : myuser1
  password : mypassword1
  TNS_ADMIN : /somefolder/Wallet_somewallet1
  # if present, OCI Vault is used for password rather than "password" attribute
#  passwordOCID :
  # the following is applicable only if OCI config file is used rather than instance principals authentication (generally only the case in development)
#  ociConfigFile :
#  ociRegion :
#  ociProfile :
dataSourceMySecondDB :
  serviceName : myservicename1
  userName : myuser2
  password : mypassword2
  TNS_ADMIN : /somefolder/Wallet_somewallet2
#  # if present, OCI Vault is used for password rather than "password" attribute
#  passwordOCID :
  # the following is applicable only if OCI config file is used rather than instance principals authentication (generally only the case in development)
#  ociConfigFile :
#  ociRegion :
#  ociProfile :