apiVersion: v1
kind: Service
metadata:
  name: observability-exporter-example
  labels:
    app: observability-exporter-example
spec:
  type: NodePort
  ports:
    - port: 8080
      name: metrics
      targetPort: 8080
  selector:
    app: observability-exporter-example
