apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-observability-exporter-example
  labels:
    app: observability-exporter-example
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: observability-exporter-example