apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-unified-observability-exporter-%EXPORTER_NAME%
  labels:
    app: unified-observability-exporter-%EXPORTER_NAME%
    release: stable
spec:
  endpoints:
    - interval: 20s
      port: metrics
  selector:
    matchLabels:
      app: unified-observability-exporter-%EXPORTER_NAME%