apiVersion: v1
kind: Service
metadata:
  name: unified-observability-exporter-service-%EXPORTER_NAME%
  labels:
    app: unified-observability-exporter-%EXPORTER_NAME%
    release: stable
spec:
  type: NodePort
  ports:
    - port: 9161
      name: metrics
  selector:
    app: unified-observability-exporter-%EXPORTER_NAME%
