{
 "title": "Oracle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Oracle Database Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SGA Max Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"sga_max_size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGA Aggregate Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"pga_aggregate_limit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sessions_value{status=\"ACTIVE\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_activity_user_commits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Execute count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_execute_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Platform",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "max(oracledb_db_platform_value) by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"cpu_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Top SQL by elapsed time running",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(oracledb_top_sql_elapsed) by (sql_id, sql_text)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Wait Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Wait time - Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_concurrency" }
   ]
  },
  {
   "title": "Wait time - Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_commit" }
   ]
  },
  {
   "title": "Wait time - System I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_system_io" }
   ]
  },
  {
   "title": "Wait time - User I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_user_io" }
   ]
  },
  {
   "title": "Wait time - Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_application" }
   ]
  },
  {
   "title": "Wait time - Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "oracledb_wait_time_network" }
   ]
  }
 ]
}