{
 "title": "Oracle Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "database", "label": "database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "title": "Oracle AI Database Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_up{database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGA Max Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"sga_max_size\", database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGA Aggregate Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"pga_aggregate_limit\", database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sessions_value{status=\"ACTIVE\", database=\"$database\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_commits{database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execute count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_execute_count{database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Platform",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "max by(platform_name) (oracledb_db_platform_value{database=\"$database\"})",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "Database Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_dbtype{database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"cpu_count\", database=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Wait Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Database Wait Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_administrative{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Administrative"
    },
    {
     "expr": "rate(oracledb_wait_time_application{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Application"
    },
    {
     "expr": "rate(oracledb_wait_time_cluster{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Cluster"
    },
    {
     "expr": "rate(oracledb_wait_time_commit{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Commit"
    },
    {
     "expr": "rate(oracledb_wait_time_concurrency{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Concurrency"
    },
    {
     "expr": "rate(oracledb_wait_time_configuration{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Configuration"
    },
    {
     "expr": "rate(oracledb_wait_time_network{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Network"
    },
    {
     "expr": "rate(oracledb_wait_time_other{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "rate(oracledb_wait_time_scheduler{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "rate(oracledb_wait_time_user_io{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "User I/O"
    },
    {
     "expr": "rate(oracledb_wait_time_system_io{database=\"$database\"}[$__rate_interval])",
     "legendFormat": "System I/O"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cache Hit Ratios",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_cache_hit_ratio_value{database=\"$database\"}",
     "legendFormat": "{{cache_hit_type}}"
    }
   ]
  },
  { "title": "Top SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top SQL by elapsed time running",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max(oracledb_top_sql_elapsed{database=\"$database\"}) by (sql_id, sql_text)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}