[[metric]]
context = "test_oracle_jobs"
metricsdesc = { last_run_duration = "Duration of Last Run"}
labels = [ "job_name", "state", "next_run_date", "last_start_date" ]
request = '''
select job_name, state, next_run_date, last_start_date, extract(second from last_run_duration) last_run_duration
  from DBA_SCHEDULER_JOBS
WHERE job_name like 'PURGE%'
'''
#scrapeinterval = "15m"

