[[metric]]
context = "test_oracle_jobs"
metricsdesc = { last_run_duration = "Duration of Last Run"}
labels = [ "job_name", "state", "next_run_date", "last_start_date" ]
request = '''
select job_name, state, next_run_date, last_start_date, last_run_duration
  from DBA_SCHEDULER_JOBS
WHERE job_name like 'EM%'
order by last_start_date desc
'''
scrapeinterval = "15m"

