[[metric]]
context = "ownership"
metricsdesc = { inst_id = "Owner instance of the current queues." }
request = '''
SELECT
    inst_id
FROM
    gv$persistent_queues
WHERE
    ROWNUM < 2
'''
ignorezeroresult = true
querytimeout = "10s"
scrapeinterval = "30s"

[[metric]]
context = "teq"
metricsdesc = { curr_inst_id = "ID of current instance" }
request = "SELECT instance_number AS curr_inst_id FROM gv$instance"
ignorezeroresult = true

[[metric]]
context = "teq"
labels = ["inst_id"]
metricsdesc = { total_queues = "Total number of queues"}
request = '''
SELECT
    inst_id,
    COUNT(*) AS total_queues
FROM
    (
        SELECT DISTINCT
            t1.inst_id,
            t2.queue_name
        FROM
            gv$aq_sharded_subscriber_stat   t1
            JOIN gv$persistent_queues            t2 ON t1.queue_id = t2.queue_id
    )
GROUP BY
    inst_id
'''
ignorezeroresult = true

[[metric]]
context = "teq"
labels = ["inst_id"]
metricsdesc = { total_subscribers = "Total number of subscribers"}
request = '''
SELECT
    inst_id,
    COUNT(*) AS total_subscribers
FROM
    (
        SELECT DISTINCT
            inst_id,
            subscriber_id
        FROM
            gv$aq_sharded_subscriber_stat
    )
GROUP BY
    inst_id
'''
ignorezeroresult = true
