name: Unit Tests And Build

on:
  pull_request_review:
    types:
      - submitted
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-build:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      )
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
      CGO_ENABLED: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event_name == 'pull_request_review' && github.event.pull_request.head.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build exporter
        run: make go-build

      - name: Run tests
        run: make go-test
